; Atom flat NOBJ 0.2 profile for native/nobj-consumer.asm.
;
; Include this file with nobj-consumer.asm when ZN_PROF should accept Atom's
; flat bank-zero profile. IX must address ZA_SIZE bytes rather than ZN_SIZE.
; The validator uses repeated sequential scans to prove PATCH coverage and
; non-overlap without retaining a bitmap or an interval table in Z80 RAM.

ZA_BASE EQU 20
ZA_CAP EQU 22
ZA_USED EQU 24
ZA_HIEND EQU 26
ZA_IMEND EQU 28
ZA_PCOUNT EQU 30
ZA_INDEX EQU 32
ZA_PSTART EQU 34
ZA_PEND EQU 36
ZA_COVER EQU 38
ZA_TMPST EQU 40
ZA_TMPEND EQU 42
ZA_WORDLO EQU 44
ZA_SIZE EQU 45

; Validate the complete Atom 0.2 profile before common materialization.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZN_PROF:
CALL ZN_REW
JP   C,ZA_FAIL
XOR  A
LD   (IX+ZA_HIEND),A
LD   (IX+ZA_HIEND+1),A
LD   (IX+ZA_IMEND),A
LD   (IX+ZA_IMEND+1),A
LD   (IX+ZA_PCOUNT),A
LD   (IX+ZA_PCOUNT+1),A
ZA_FIRST:
CALL ZA_HEAD
JP   C,ZA_FAIL
CP   ZN_BEGIN
JP   Z,ZA_BEGIN
CP   ZN_IMAGE
JP   Z,ZA_IMAGE
CP   ZN_PATCH
JP   Z,ZA_PATCH
CP   ZN_MAP
JP   Z,ZA_MAP
CP   ZN_COMMIT
JP   Z,ZA_PATCHES
JP   ZA_FAIL

ZA_BEGIN:
LD   A,(IX+ZN_LENLO)
CP   15
JP   NZ,ZA_FAIL
LD   A,(IX+ZN_LENHI)
OR   A
JP   NZ,ZA_FAIL
LD   HL,6
CALL ZA_SKIPN
JP   C,ZA_FAIL
CALL ZN_READ
JP   C,ZA_FAIL
OR   A
JP   NZ,ZA_FAIL
CALL ZA_WORD
JP   C,ZA_FAIL
LD   A,H
OR   L
JP   NZ,ZA_FAIL
CALL ZN_READ
JP   C,ZA_FAIL
CP   1
JP   NZ,ZA_FAIL
CALL ZN_READ
JP   C,ZA_FAIL
CALL ZA_WORD
JP   C,ZA_FAIL
LD   (IX+ZA_BASE),L
LD   (IX+ZA_BASE+1),H
CALL ZA_WORD
JP   C,ZA_FAIL
LD   A,H
OR   L
JP   Z,ZA_FAIL
LD   (IX+ZA_CAP),L
LD   (IX+ZA_CAP+1),H
LD   E,(IX+ZA_BASE)
LD   D,(IX+ZA_BASE+1)
ADD  HL,DE
JP   NC,ZA_FIRST
LD   A,H
OR   L
JP   NZ,ZA_FAIL
JP   ZA_FIRST

ZA_IMAGE:
CALL ZA_RANGE
JP   C,ZA_FAIL
LD   L,(IX+ZA_TMPST)
LD   H,(IX+ZA_TMPST+1)
LD   E,(IX+ZA_IMEND)
LD   D,(IX+ZA_IMEND+1)
OR   A
SBC  HL,DE
JP   C,ZA_FAIL
LD   L,(IX+ZA_TMPEND)
LD   H,(IX+ZA_TMPEND+1)
LD   (IX+ZA_IMEND),L
LD   (IX+ZA_IMEND+1),H
CALL ZA_HIGH
CALL ZN_SKIP
JP   C,ZA_FAIL
JP   ZA_FIRST

ZA_PATCH:
CALL ZA_RANGE
JP   C,ZA_FAIL
LD   L,(IX+ZA_PCOUNT)
LD   H,(IX+ZA_PCOUNT+1)
INC  HL
LD   A,H
OR   L
JP   Z,ZA_FAIL
LD   (IX+ZA_PCOUNT),L
LD   (IX+ZA_PCOUNT+1),H
CALL ZA_HIGH
CALL ZN_SKIP
JP   C,ZA_FAIL
JP   ZA_FIRST

ZA_MAP:
LD   L,(IX+ZN_LENLO)
LD   H,(IX+ZN_LENHI)
LD   DE,11
OR   A
SBC  HL,DE
JP   C,ZA_FAIL
CALL ZN_READ
JP   C,ZA_FAIL
CP   $41
JP   NZ,ZA_FAIL
CALL ZN_READ
JP   C,ZA_FAIL
OR   A
JP   NZ,ZA_FAIL
CALL ZN_READ
JP   C,ZA_FAIL
OR   A
JP   NZ,ZA_FAIL
CALL ZA_WORD
JP   C,ZA_FAIL
LD   A,L
CP   (IX+ZN_ENTLO)
JP   NZ,ZA_FAIL
LD   A,H
CP   (IX+ZN_ENTHI)
JP   NZ,ZA_FAIL
LD   E,(IX+ZA_BASE)
LD   D,(IX+ZA_BASE+1)
OR   A
SBC  HL,DE
JP   C,ZA_FAIL
EX   DE,HL
LD   L,(IX+ZA_CAP)
LD   H,(IX+ZA_CAP+1)
OR   A
SBC  HL,DE
JP   C,ZA_FAIL
LD   A,H
OR   L
JP   Z,ZA_FAIL
CALL ZA_WORD
JP   C,ZA_FAIL
LD   (IX+ZA_USED),L
LD   (IX+ZA_USED+1),H
LD   E,(IX+ZA_CAP)
LD   D,(IX+ZA_CAP+1)
EX   DE,HL
OR   A
SBC  HL,DE
JP   C,ZA_FAIL
LD   L,(IX+ZA_USED)
LD   H,(IX+ZA_USED+1)
LD   E,(IX+ZA_HIEND)
LD   D,(IX+ZA_HIEND+1)
OR   A
SBC  HL,DE
JP   C,ZA_FAIL
CALL ZA_WORD
JP   C,ZA_FAIL
LD   E,(IX+ZA_BASE)
LD   D,(IX+ZA_BASE+1)
OR   A
SBC  HL,DE
JP   C,ZA_FAIL
LD   E,(IX+ZA_CAP)
LD   D,(IX+ZA_CAP+1)
EX   DE,HL
OR   A
SBC  HL,DE
JP   C,ZA_FAIL
CALL ZN_READ
JP   C,ZA_FAIL
OR   A
JP   Z,ZA_FAIL
LD   (IX+ZN_REMLO),A
LD   L,A
LD   H,0
LD   DE,10
ADD  HL,DE
LD   A,L
CP   (IX+ZN_LENLO)
JP   NZ,ZA_FAIL
LD   A,H
CP   (IX+ZN_LENHI)
JP   NZ,ZA_FAIL
ZA_MAPBANK:
CALL ZN_READ
JP   C,ZA_FAIL
OR   A
JP   NZ,ZA_FAIL
DEC  (IX+ZN_REMLO)
JP   NZ,ZA_MAPBANK
JP   ZA_FIRST

; Prove every patch against the retained IMAGE stream and all earlier patches.
ZA_PATCHES:
XOR  A
LD   (IX+ZA_INDEX),A
LD   (IX+ZA_INDEX+1),A
ZA_PNEXT:
LD   L,(IX+ZA_INDEX)
LD   H,(IX+ZA_INDEX+1)
LD   E,(IX+ZA_PCOUNT)
LD   D,(IX+ZA_PCOUNT+1)
OR   A
SBC  HL,DE
JP   Z,ZA_OK
CALL ZA_FINDP
JP   C,ZA_FAIL
CALL ZA_SCAN
JP   C,ZA_FAIL
LD   L,(IX+ZA_INDEX)
LD   H,(IX+ZA_INDEX+1)
INC  HL
LD   (IX+ZA_INDEX),L
LD   (IX+ZA_INDEX+1),H
JR   ZA_PNEXT

; Locate the selected PATCH and retain its relative interval.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZA_FINDP:
CALL ZN_REW
RET  C
XOR  A
LD   (IX+ZA_COVER),A
LD   (IX+ZA_COVER+1),A
ZA_FIND0:
CALL ZA_HEAD
RET  C
CP   ZN_PATCH
JR   Z,ZA_FIND1
CP   ZN_COMMIT
JP   Z,ZA_BAD
CALL ZN_SETREM
CALL ZN_SKIP
RET  C
JR   ZA_FIND0
ZA_FIND1:
CALL ZA_RANGE
RET  C
LD   L,(IX+ZA_COVER)
LD   H,(IX+ZA_COVER+1)
LD   E,(IX+ZA_INDEX)
LD   D,(IX+ZA_INDEX+1)
OR   A
SBC  HL,DE
JR   Z,ZA_FOUND
LD   L,(IX+ZA_COVER)
LD   H,(IX+ZA_COVER+1)
INC  HL
LD   (IX+ZA_COVER),L
LD   (IX+ZA_COVER+1),H
CALL ZN_SKIP
RET  C
JR   ZA_FIND0
ZA_FOUND:
LD   L,(IX+ZA_TMPST)
LD   H,(IX+ZA_TMPST+1)
LD   (IX+ZA_PSTART),L
LD   (IX+ZA_PSTART+1),H
LD   L,(IX+ZA_TMPEND)
LD   H,(IX+ZA_TMPEND+1)
LD   (IX+ZA_PEND),L
LD   (IX+ZA_PEND+1),H
CALL ZN_SKIP
RET

; Scan IMAGE coverage and compare the selected patch with prior patches.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZA_SCAN:
CALL ZN_REW
RET  C
LD   L,(IX+ZA_PSTART)
LD   H,(IX+ZA_PSTART+1)
LD   (IX+ZA_COVER),L
LD   (IX+ZA_COVER+1),H
XOR  A
LD   (IX+ZA_TMPST),A
LD   (IX+ZA_TMPST+1),A
LD   (IX+ZN_ADDRLO),A
LD   (IX+ZN_ADDRHI),A
ZA_SCAN0:
CALL ZA_HEAD
RET  C
CP   ZN_IMAGE
JR   Z,ZA_SCIMG
CP   ZN_PATCH
JR   Z,ZA_SCPAT
CP   ZN_MAP
JP   Z,ZA_SCDONE
CALL ZN_SETREM
CALL ZN_SKIP
RET  C
JP   ZA_SCAN0
ZA_SCIMG:
CALL ZA_RANGE
RET  C
LD   L,(IX+ZA_COVER)
LD   H,(IX+ZA_COVER+1)
LD   E,(IX+ZA_PEND)
LD   D,(IX+ZA_PEND+1)
OR   A
SBC  HL,DE
JR   NC,ZA_SCSKIP
LD   L,(IX+ZA_TMPEND)
LD   H,(IX+ZA_TMPEND+1)
LD   E,(IX+ZA_COVER)
LD   D,(IX+ZA_COVER+1)
OR   A
SBC  HL,DE
JR   C,ZA_SCSKIP
JR   Z,ZA_SCSKIP
LD   L,(IX+ZA_TMPST)
LD   H,(IX+ZA_TMPST+1)
OR   A
SBC  HL,DE
JR   Z,ZA_SCCOVER
JR   C,ZA_SCCOVER
JR   ZA_BAD
ZA_SCCOVER:
LD   L,(IX+ZA_TMPEND)
LD   H,(IX+ZA_TMPEND+1)
LD   (IX+ZA_COVER),L
LD   (IX+ZA_COVER+1),H
ZA_SCSKIP:
CALL ZN_SKIP
RET  C
JR   ZA_SCAN0
ZA_SCPAT:
CALL ZA_RANGE
RET  C
LD   L,(IX+ZA_TMPST)
LD   H,(IX+ZA_TMPST+1)
LD   E,(IX+ZA_INDEX)
LD   D,(IX+ZA_INDEX+1)
; ZA_TMPST currently holds the interval start, so use the record ordinal in
; ZN_REM after saving the data length is not possible. Count ordinals in the
; common address scratch after the range has been retained.
LD   L,(IX+ZN_ADDRLO)
LD   H,(IX+ZN_ADDRHI)
OR   A
SBC  HL,DE
JR   NC,ZA_SCPASS
LD   L,(IX+ZA_TMPST)
LD   H,(IX+ZA_TMPST+1)
LD   E,(IX+ZA_PEND)
LD   D,(IX+ZA_PEND+1)
OR   A
SBC  HL,DE
JR   NC,ZA_SCPASS
LD   L,(IX+ZA_PSTART)
LD   H,(IX+ZA_PSTART+1)
LD   E,(IX+ZA_TMPEND)
LD   D,(IX+ZA_TMPEND+1)
OR   A
SBC  HL,DE
JR   C,ZA_BAD
ZA_SCPASS:
LD   L,(IX+ZN_ADDRLO)
LD   H,(IX+ZN_ADDRHI)
INC  HL
LD   (IX+ZN_ADDRLO),L
LD   (IX+ZN_ADDRHI),H
CALL ZN_SKIP
RET  C
JP   ZA_SCAN0
ZA_SCDONE:
LD   L,(IX+ZA_COVER)
LD   H,(IX+ZA_COVER+1)
LD   E,(IX+ZA_PEND)
LD   D,(IX+ZA_PEND+1)
OR   A
SBC  HL,DE
RET  NC
ZA_BAD:
SCF
RET

; Read and retain one record header.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZA_HEAD:
CALL ZN_READ
RET  C
LD   (IX+ZN_KIND),A
CALL ZN_READ
RET  C
LD   (IX+ZN_LENLO),A
CALL ZN_READ
RET  C
LD   (IX+ZN_LENHI),A
LD   A,(IX+ZN_KIND)
OR   A
RET

; Read an IMAGE/PATCH prefix and calculate its relative half-open interval.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZA_RANGE:
LD   L,(IX+ZN_LENLO)
LD   H,(IX+ZN_LENHI)
LD   DE,3
OR   A
SBC  HL,DE
RET  C
LD   A,H
OR   L
SCF
RET  Z
LD   (IX+ZN_REMLO),L
LD   (IX+ZN_REMHI),H
CALL ZN_READ
RET  C
OR   A
SCF
RET  NZ
CALL ZA_WORD
RET  C
LD   E,(IX+ZA_BASE)
LD   D,(IX+ZA_BASE+1)
OR   A
SBC  HL,DE
RET  C
LD   (IX+ZA_TMPST),L
LD   (IX+ZA_TMPST+1),H
LD   E,(IX+ZN_REMLO)
LD   D,(IX+ZN_REMHI)
ADD  HL,DE
RET  C
LD   (IX+ZA_TMPEND),L
LD   (IX+ZA_TMPEND+1),H
LD   E,(IX+ZA_CAP)
LD   D,(IX+ZA_CAP+1)
EX   DE,HL
OR   A
SBC  HL,DE
RET

; Raise the retained highest record end.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZA_HIGH:
LD   L,(IX+ZA_TMPEND)
LD   H,(IX+ZA_TMPEND+1)
LD   E,(IX+ZA_HIEND)
LD   D,(IX+ZA_HIEND+1)
OR   A
SBC  HL,DE
RET  C
LD   L,(IX+ZA_TMPEND)
LD   H,(IX+ZA_TMPEND+1)
LD   (IX+ZA_HIEND),L
LD   (IX+ZA_HIEND+1),H
RET

; Read a little-endian word.
;@ROUTINE IN IX OUT A,HL,CARRY CLOBBERS BC,DE,ZERO,SIGN,PARITY,HALFCARRY
ZA_WORD:
CALL ZN_READ
RET  C
LD   (IX+ZA_WORDLO),A
CALL ZN_READ
RET  C
LD   H,A
LD   L,(IX+ZA_WORDLO)
OR   A
RET

; Skip exactly HL bytes.
;@ROUTINE IN IX,HL OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZA_SKIPN:
LD   (IX+ZN_REMLO),L
LD   (IX+ZN_REMHI),H
JP   ZN_SKIP

ZA_OK:
XOR  A
RET
ZA_FAIL:
SCF
RET

ZA_END:
