; Nucleus NOBJ 0.1 profile for native/nobj-consumer.asm.
;
; Include this file with nobj-consumer.asm when ZN_PROF should accept the
; complete flat or banked Nucleus profile. IX addresses NN_SIZE bytes.
; Validation retains no bank or patch table: it rescans the immutable stored
; object for each bank and patch, keeping RAM use constant through 255 banks.

NB_FLAGS EQU 20
NB_BANKS EQU 21
NB_FILL EQU 22
NB_BASE EQU 23
NB_CAP EQU 25
NB_TEND EQU 27
NB_T64 EQU 29
NM_FLAGS EQU 30
NM_ENTRYBANK EQU 31
NM_ENTRY EQU 32
NM_WBASE EQU 34
NM_WCAP EQU 36
NM_WEND EQU 38
NM_W64 EQU 40
NM_VECTOR EQU 41
NM_VLEN EQU 43
NM_INIT EQU 45
NM_ILEN EQU 47
NM_IEND EQU 49
NM_BSSEND EQU 51
NM_BSS64 EQU 53
NM_STACK EQU 54
NM_LOADBANK EQU 56
NM_LOAD EQU 57
NM_LOADLEN EQU 59
NM_PARTS EQU 61
NN_PATCHES EQU 62
NN_BANKINDEX EQU 64
NN_USED EQU 65
NN_ROBASE EQU 67
NN_ROLEN EQU 69
NN_AGBASE EQU 71
NN_AGLEN EQU 73
NN_TMPBANK EQU 75
NN_TMPST EQU 76
NN_TMPEND EQU 78
NN_PREV EQU 80
NN_HIGH EQU 82
NN_PATCHINDEX EQU 84
NN_ORDINAL EQU 86
NN_PBANK EQU 88
NN_PSTART EQU 89
NN_PEND EQU 91
NN_WORDLO EQU 93
NN_SIZE EQU 94

; Validate the complete Nucleus 0.1 profile before common materialization.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZN_PROF:
CALL ZN_REW
JP   C,NN_FAIL
XOR  A
LD   (IX+NN_PATCHES),A
LD   (IX+NN_PATCHES+1),A
NN_FIRST:
CALL NN_HEAD
JP   C,NN_FAIL
CP   ZN_BEGIN
JP   Z,NN_BEGIN
CP   ZN_IMAGE
JP   Z,NN_IMAGE
CP   ZN_PATCH
JP   Z,NN_PATCH
CP   ZN_MAP
JP   Z,NN_MAP
JP   NN_FAIL

NN_BEGIN:
LD   A,(IX+ZN_LENLO)
CP   15
JP   NZ,NN_FAIL
LD   A,(IX+ZN_LENHI)
OR   A
JP   NZ,NN_FAIL
LD   HL,6
CALL NN_SKIPN
JP   C,NN_FAIL
CALL ZN_READ
JP   C,NN_FAIL
LD   (IX+NB_FLAGS),A
AND  $FE
JP   NZ,NN_FAIL
LD   HL,2
CALL NN_SKIPN
JP   C,NN_FAIL
CALL ZN_READ
JP   C,NN_FAIL
LD   (IX+NB_BANKS),A
OR   A
JP   Z,NN_FAIL
LD   B,A
LD   A,(IX+NB_FLAGS)
AND  1
JR   Z,NN_BEGINFLAT
LD   A,B
CP   2
JP   C,NN_FAIL
JR   NN_BEGINBANKS
NN_BEGINFLAT:
LD   A,B
CP   1
JP   NZ,NN_FAIL
NN_BEGINBANKS:
CALL ZN_READ
JP   C,NN_FAIL
LD   (IX+NB_FILL),A
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NB_BASE),L
LD   (IX+NB_BASE+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   A,H
OR   L
JP   Z,NN_FAIL
LD   (IX+NB_CAP),L
LD   (IX+NB_CAP+1),H
LD   E,(IX+NB_BASE)
LD   D,(IX+NB_BASE+1)
ADD  HL,DE
LD   (IX+NB_TEND),L
LD   (IX+NB_TEND+1),H
LD   A,0
ADC  A,0
LD   (IX+NB_T64),A
JR   NC,NN_BEGINSTATE
LD   A,H
OR   L
JP   NZ,NN_FAIL
NN_BEGINSTATE:
; The common/profile state must not be overwritten while a bank is selected.
PUSH IX
POP  HL
LD   DE,NN_SIZE
ADD  HL,DE
JR   NC,NN_STATEEND16
LD   A,H
OR   L
JP   NZ,NN_FAIL
JR   NN_STATESECOND
NN_STATEEND16:
EX   DE,HL
LD   L,(IX+NB_BASE)
LD   H,(IX+NB_BASE+1)
OR   A
SBC  HL,DE
JP   NC,NN_FIRST
NN_STATESECOND:
LD   A,(IX+NB_T64)
OR   A
JP   NZ,NN_FAIL
PUSH IX
POP  HL
LD   E,(IX+NB_TEND)
LD   D,(IX+NB_TEND+1)
OR   A
SBC  HL,DE
JP   C,NN_FAIL
JP   NN_FIRST

NN_IMAGE:
CALL NN_RANGE
JP   C,NN_FAIL
CALL ZN_SKIP
JP   C,NN_FAIL
JP   NN_FIRST

NN_PATCH:
CALL NN_RANGE
JP   C,NN_FAIL
LD   L,(IX+NN_PATCHES)
LD   H,(IX+NN_PATCHES+1)
INC  HL
LD   A,H
OR   L
JP   Z,NN_FAIL
LD   (IX+NN_PATCHES),L
LD   (IX+NN_PATCHES+1),H
CALL ZN_SKIP
JP   C,NN_FAIL
JP   NN_FIRST

; Read and validate the MAP prefix and its variable record shape.
NN_MAP:
CALL ZN_READ
JP   C,NN_FAIL
CP   1
JP   NZ,NN_FAIL
CALL ZN_READ
JP   C,NN_FAIL
LD   (IX+NM_FLAGS),A
AND  $FC
JP   NZ,NN_FAIL
CALL ZN_READ
JP   C,NN_FAIL
LD   (IX+NM_ENTRYBANK),A
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_ENTRY),L
LD   (IX+NM_ENTRY+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_WBASE),L
LD   (IX+NM_WBASE+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   A,H
OR   L
JP   Z,NN_FAIL
LD   (IX+NM_WCAP),L
LD   (IX+NM_WCAP+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_VECTOR),L
LD   (IX+NM_VECTOR+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_VLEN),L
LD   (IX+NM_VLEN+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_INIT),L
LD   (IX+NM_INIT+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_ILEN),L
LD   (IX+NM_ILEN+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   B,H
LD   C,L
LD   L,(IX+NM_INIT)
LD   H,(IX+NM_INIT+1)
LD   E,(IX+NM_ILEN)
LD   D,(IX+NM_ILEN+1)
ADD  HL,DE
JP   C,NN_FAIL
LD   (IX+NM_IEND),L
LD   (IX+NM_IEND+1),H
OR   A
SBC  HL,BC
JP   NZ,NN_FAIL
CALL NN_WORD
JP   C,NN_FAIL
LD   B,H
LD   C,L
LD   L,(IX+NM_IEND)
LD   H,(IX+NM_IEND+1)
ADD  HL,BC
LD   (IX+NM_BSSEND),L
LD   (IX+NM_BSSEND+1),H
LD   A,0
JR   NC,NN_MAPBSS64
INC  A
NN_MAPBSS64:
LD   (IX+NM_BSS64),A
JR   NC,NN_MAPSTACK
LD   A,H
OR   L
JP   NZ,NN_FAIL
NN_MAPSTACK:
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_STACK),L
LD   (IX+NM_STACK+1),H
CALL ZN_READ
JP   C,NN_FAIL
LD   (IX+NM_LOADBANK),A
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_LOAD),L
LD   (IX+NM_LOAD+1),H
CALL NN_WORD
JP   C,NN_FAIL
LD   (IX+NM_LOADLEN),L
LD   (IX+NM_LOADLEN+1),H
CALL ZN_READ
JP   C,NN_FAIL
OR   A
JP   Z,NN_FAIL
LD   (IX+NM_PARTS),A
LD   (IX+ZN_BANK),A
NN_MAPPART:
CALL ZN_READ
JP   C,NN_FAIL
CP   (IX+NB_BANKS)
JP   NC,NN_FAIL
DEC  (IX+ZN_BANK)
JP   NZ,NN_MAPPART
CALL ZN_READ
JP   C,NN_FAIL
CP   (IX+NB_BANKS)
JP   NZ,NN_FAIL
; Exact length is 30 + partCount + 10 * bankCount.
LD   L,A
LD   H,0
ADD  HL,HL
LD   D,H
LD   E,L
ADD  HL,HL
ADD  HL,HL
ADD  HL,DE
LD   A,(IX+NM_PARTS)
LD   E,A
LD   D,0
ADD  HL,DE
LD   DE,30
ADD  HL,DE
LD   A,L
CP   (IX+ZN_LENLO)
JP   NZ,NN_FAIL
LD   A,H
CP   (IX+ZN_LENHI)
JP   NZ,NN_FAIL
LD   A,(IX+NB_BANKS)
LD   (IX+ZN_BANK),A
NN_MAPSKIP:
LD   HL,10
CALL NN_SKIPN
JP   C,NN_FAIL
DEC  (IX+ZN_BANK)
JP   NZ,NN_MAPSKIP
PUSH IX
PUSH IY
CALL NN_MAPFIXED
POP  IY
POP  IX
JP   C,NN_FAIL
CALL NN_HEAD
JP   C,NN_FAIL
CP   ZN_COMMIT
JP   NZ,NN_FAIL
LD   A,(IX+NM_ENTRYBANK)
CP   (IX+ZN_ENTBNK)
JP   NZ,NN_FAIL
LD   A,(IX+NM_ENTRY)
CP   (IX+ZN_ENTLO)
JP   NZ,NN_FAIL
LD   A,(IX+NM_ENTRY+1)
CP   (IX+ZN_ENTHI)
JP   NZ,NN_FAIL
CALL NN_BANKS
JP   C,NN_FAIL
CALL NN_PATCHCHECK
RET  C
XOR  A
RET

; Validate MAP relationships that do not depend on per-bank entries.
; AZM 0.3.9 conservatively loses indexed-register preservation across the
; conditional shared exits below. The caller saves both index registers.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,IXH,IXL,IYH,IYL,ZERO,SIGN,PARITY,HALFCARRY
NN_MAPFIXED:
LD   A,(IX+NM_ENTRYBANK)
LD   B,(IX+NB_BANKS)
CP   B
JP   NC,NN_BAD
LD   A,(IX+NM_LOADBANK)
LD   B,(IX+NB_BANKS)
CP   B
JP   NC,NN_BAD
LD   A,(IX+NB_FLAGS)
AND  1
JR   Z,NN_MFFLAT
LD   A,(IX+NM_FLAGS)
AND  1
JP   Z,NN_BAD
JR   NN_MFMODE
NN_MFFLAT:
LD   A,(IX+NM_ENTRYBANK)
OR   A
JP   NZ,NN_BAD
NN_MFMODE:
LD   L,(IX+NM_WBASE)
LD   H,(IX+NM_WBASE+1)
LD   E,(IX+NM_WCAP)
LD   D,(IX+NM_WCAP+1)
ADD  HL,DE
LD   (IX+NM_WEND),L
LD   (IX+NM_WEND+1),H
LD   A,0
JR   NC,NN_MFW64
INC  A
NN_MFW64:
LD   (IX+NM_W64),A
JR   NC,NN_MFREGION
LD   A,H
OR   L
JP   NZ,NN_BAD
NN_MFREGION:
LD   A,(IX+NM_FLAGS)
AND  1
JR   Z,NN_MFLOADED
; ROM mode requires disjoint image and writable intervals.
LD   A,(IX+NM_W64)
OR   A
JR   NZ,NN_MFROM1
LD   L,(IX+NB_BASE)
LD   H,(IX+NB_BASE+1)
LD   E,(IX+NM_WEND)
LD   D,(IX+NM_WEND+1)
OR   A
SBC  HL,DE
JR   NC,NN_MFVECTORS
NN_MFROM1:
LD   A,(IX+NB_T64)
OR   A
JP   NZ,NN_BAD
LD   L,(IX+NM_WBASE)
LD   H,(IX+NM_WBASE+1)
LD   E,(IX+NB_TEND)
LD   D,(IX+NB_TEND+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
JR   NN_MFVECTORS
NN_MFLOADED:
; Loaded mode requires the writable interval wholly inside the image interval.
LD   L,(IX+NM_WBASE)
LD   H,(IX+NM_WBASE+1)
LD   E,(IX+NB_BASE)
LD   D,(IX+NB_BASE+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
LD   A,(IX+NM_W64)
OR   A
JR   Z,NN_MFLEND16
LD   A,(IX+NB_T64)
OR   A
JP   Z,NN_BAD
JR   NN_MFVECTORS
NN_MFLEND16:
LD   A,(IX+NB_T64)
OR   A
JR   NZ,NN_MFVECTORS
LD   L,(IX+NB_TEND)
LD   H,(IX+NB_TEND+1)
LD   E,(IX+NM_WEND)
LD   D,(IX+NM_WEND+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
NN_MFVECTORS:
LD   L,(IX+NM_VECTOR)
LD   H,(IX+NM_VECTOR+1)
LD   E,(IX+NM_WBASE)
LD   D,(IX+NM_WBASE+1)
OR   A
SBC  HL,DE
JP   NZ,NN_BAD
LD   L,(IX+NM_INIT)
LD   H,(IX+NM_INIT+1)
LD   E,(IX+NM_WBASE)
LD   D,(IX+NM_WBASE+1)
OR   A
SBC  HL,DE
JP   NZ,NN_BAD
LD   L,(IX+NM_VLEN)
LD   H,(IX+NM_VLEN+1)
LD   A,H
OR   L
JP   Z,NN_BAD
LD   E,(IX+NM_ILEN)
LD   D,(IX+NM_ILEN+1)
EX   DE,HL
OR   A
SBC  HL,DE
JP   C,NN_BAD
; initializedRunBase + initializedRunLength must be representable as bssBase.
LD   L,(IX+NM_INIT)
LD   H,(IX+NM_INIT+1)
LD   E,(IX+NM_ILEN)
LD   D,(IX+NM_ILEN+1)
ADD  HL,DE
JP   C,NN_BAD
LD   (IX+NM_IEND),L
LD   (IX+NM_IEND+1),H
; initialized/BSS must start within and end no later than writableEnd.
LD   L,(IX+NM_INIT)
LD   H,(IX+NM_INIT+1)
LD   E,(IX+NM_WBASE)
LD   D,(IX+NM_WBASE+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
LD   A,(IX+NM_BSS64)
OR   A
JR   Z,NN_MFBSS16
LD   A,(IX+NM_W64)
OR   A
JP   Z,NN_BAD
JR   NN_MFSTACK
NN_MFBSS16:
LD   A,(IX+NM_W64)
OR   A
JR   NZ,NN_MFSTACK
LD   L,(IX+NM_WEND)
LD   H,(IX+NM_WEND+1)
LD   E,(IX+NM_BSSEND)
LD   D,(IX+NM_BSSEND+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
NN_MFSTACK:
LD   A,(IX+NM_FLAGS)
AND  2
JR   Z,NN_MFLOAD
; Available bytes above BSS must cover stackRequirement + the initial word.
LD   L,(IX+NM_STACK)
LD   H,(IX+NM_STACK+1)
LD   DE,2
ADD  HL,DE
JP   C,NN_BAD
EX   DE,HL
LD   A,(IX+NM_W64)
OR   A
JR   Z,NN_MFAVAIL16
LD   HL,0
JR   NN_MFAVAILSUB
NN_MFAVAIL16:
LD   L,(IX+NM_WEND)
LD   H,(IX+NM_WEND+1)
NN_MFAVAILSUB:
LD   A,(IX+NM_BSS64)
OR   A
JP   NZ,NN_BAD
LD   C,(IX+NM_BSSEND)
LD   B,(IX+NM_BSSEND+1)
OR   A
SBC  HL,BC
OR   A
SBC  HL,DE
JP   C,NN_BAD
NN_MFLOAD:
LD   L,(IX+NM_LOADLEN)
LD   H,(IX+NM_LOADLEN+1)
LD   E,(IX+NM_ILEN)
LD   D,(IX+NM_ILEN+1)
OR   A
SBC  HL,DE
JP   NZ,NN_BAD
LD   A,(IX+NM_FLAGS)
AND  1
JR   NZ,NN_MFROMLOAD
LD   A,(IX+NM_LOADBANK)
OR   A
JP   NZ,NN_BAD
LD   L,(IX+NM_LOAD)
LD   H,(IX+NM_LOAD+1)
LD   E,(IX+NM_INIT)
LD   D,(IX+NM_INIT+1)
OR   A
SBC  HL,DE
JP   NZ,NN_BAD
JR   NN_MFOK
NN_MFROMLOAD:
LD   A,(IX+NB_FLAGS)
AND  1
JR   Z,NN_MFOK
LD   A,(IX+NM_LOADBANK)
LD   B,(IX+NM_ENTRYBANK)
CP   B
JP   NZ,NN_BAD
NN_MFOK:
XOR  A
RET
;@ROUTINE IN IX OUT CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
@NN_BAD:
SCF
RET

; Validate every bank entry and rescan its IMAGE/PATCH records.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_BANKS:
XOR  A
LD   (IX+NN_BANKINDEX),A
NN_BANKNEXT:
CALL NN_BANKENTRY
RET  C
CALL NN_SCANBANK
RET  C
INC  (IX+NN_BANKINDEX)
LD   A,(IX+NN_BANKINDEX)
CP   (IX+NB_BANKS)
JR   C,NN_BANKNEXT
XOR  A
RET

; Locate and retain the selected ten-byte MAP bank entry.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_BANKENTRY:
CALL ZN_REW
RET  C
NN_BEHEAD:
CALL NN_HEAD
RET  C
CP   ZN_MAP
JR   Z,NN_BEFOUND
CALL ZN_SETREM
CALL ZN_SKIP
RET  C
JR   NN_BEHEAD
NN_BEFOUND:
LD   HL,29
CALL NN_SKIPN
RET  C
LD   A,(IX+NM_PARTS)
LD   L,A
LD   H,0
CALL NN_SKIPN
RET  C
CALL ZN_READ
RET  C
LD   A,(IX+NN_BANKINDEX)
LD   L,A
LD   H,0
ADD  HL,HL
LD   D,H
LD   E,L
ADD  HL,HL
ADD  HL,HL
ADD  HL,DE
CALL NN_SKIPN
RET  C
CALL NN_WORD
RET  C
LD   (IX+NN_USED),L
LD   (IX+NN_USED+1),H
CALL NN_WORD
RET  C
LD   (IX+NN_ROBASE),L
LD   (IX+NN_ROBASE+1),H
CALL NN_WORD
RET  C
LD   (IX+NN_ROLEN),L
LD   (IX+NN_ROLEN+1),H
CALL NN_WORD
RET  C
LD   (IX+NN_AGBASE),L
LD   (IX+NN_AGBASE+1),H
CALL NN_WORD
RET  C
LD   (IX+NN_AGLEN),L
LD   (IX+NN_AGLEN+1),H
XOR  A
RET

; Check record ordering/high water and the retained bank entry.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_SCANBANK:
LD   L,(IX+NN_USED)
LD   H,(IX+NN_USED+1)
LD   A,H
OR   L
JP   Z,NN_BAD
LD   E,(IX+NB_CAP)
LD   D,(IX+NB_CAP+1)
EX   DE,HL
OR   A
SBC  HL,DE
JP   C,NN_BAD
XOR  A
LD   (IX+NN_PREV),A
LD   (IX+NN_PREV+1),A
LD   (IX+NN_HIGH),A
LD   (IX+NN_HIGH+1),A
CALL ZN_REW
RET  C
NN_SBHEAD:
CALL NN_HEAD
RET  C
CP   ZN_IMAGE
JR   Z,NN_SBIMAGE
CP   ZN_PATCH
JR   Z,NN_SBPATCH
CP   ZN_MAP
JR   Z,NN_SBDONE
CALL ZN_SETREM
CALL ZN_SKIP
RET  C
JP   NN_SBHEAD
NN_SBIMAGE:
CALL NN_RANGE
RET  C
LD   A,(IX+NN_TMPBANK)
CP   (IX+NN_BANKINDEX)
JR   NZ,NN_SBSKIP
LD   L,(IX+NN_TMPST)
LD   H,(IX+NN_TMPST+1)
LD   E,(IX+NN_PREV)
LD   D,(IX+NN_PREV+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
LD   L,(IX+NN_TMPEND)
LD   H,(IX+NN_TMPEND+1)
LD   (IX+NN_PREV),L
LD   (IX+NN_PREV+1),H
JR   NN_SBHIGH
NN_SBPATCH:
CALL NN_RANGE
RET  C
LD   A,(IX+NN_TMPBANK)
CP   (IX+NN_BANKINDEX)
JR   NZ,NN_SBSKIP
NN_SBHIGH:
LD   L,(IX+NN_TMPEND)
LD   H,(IX+NN_TMPEND+1)
LD   E,(IX+NN_USED)
LD   D,(IX+NN_USED+1)
OR   A
SBC  HL,DE
JP   C,NN_SBHIGH0
JP   NZ,NN_BAD
NN_SBHIGH0:
LD   L,(IX+NN_TMPEND)
LD   H,(IX+NN_TMPEND+1)
LD   E,(IX+NN_HIGH)
LD   D,(IX+NN_HIGH+1)
OR   A
SBC  HL,DE
JR   C,NN_SBSKIP
LD   L,(IX+NN_TMPEND)
LD   H,(IX+NN_TMPEND+1)
LD   (IX+NN_HIGH),L
LD   (IX+NN_HIGH+1),H
NN_SBSKIP:
CALL ZN_SKIP
RET  C
JP   NN_SBHEAD
NN_SBDONE:
LD   L,(IX+NN_HIGH)
LD   H,(IX+NN_HIGH+1)
LD   E,(IX+NN_USED)
LD   D,(IX+NN_USED+1)
OR   A
SBC  HL,DE
JP   NZ,NN_BAD
CALL NN_OPTIONALRO
RET  C
CALL NN_BANKSPECIAL
RET

; Validate read-only and aggregate-constant optional extents.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_OPTIONALRO:
LD   L,(IX+NN_ROBASE)
LD   H,(IX+NN_ROBASE+1)
LD   E,(IX+NN_ROLEN)
LD   D,(IX+NN_ROLEN+1)
CALL NN_OPTIONAL
RET  C
LD   L,(IX+NN_AGBASE)
LD   H,(IX+NN_AGBASE+1)
LD   E,(IX+NN_AGLEN)
LD   D,(IX+NN_AGLEN+1)
CALL NN_OPTIONAL
RET  C
LD   L,(IX+NN_AGLEN)
LD   H,(IX+NN_AGLEN+1)
LD   A,H
OR   L
RET  Z
LD   L,(IX+NN_ROLEN)
LD   H,(IX+NN_ROLEN+1)
LD   A,H
OR   L
JP   Z,NN_BAD
LD   L,(IX+NN_AGBASE)
LD   H,(IX+NN_AGBASE+1)
LD   E,(IX+NN_ROBASE)
LD   D,(IX+NN_ROBASE+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
LD   E,(IX+NN_AGLEN)
LD   D,(IX+NN_AGLEN+1)
ADD  HL,DE
JP   C,NN_BAD
LD   E,(IX+NN_ROLEN)
LD   D,(IX+NN_ROLEN+1)
EX   DE,HL
OR   A
SBC  HL,DE
RET

; HL=base, DE=length. Zero length requires zero base; otherwise fit used image.
;@ROUTINE IN IX,HL,DE OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_OPTIONAL:
LD   A,D
OR   E
JR   NZ,NN_OPTNONZERO
LD   A,H
OR   L
RET  Z
SCF
RET
NN_OPTNONZERO:
LD   C,E
LD   B,D
LD   E,(IX+NB_BASE)
LD   D,(IX+NB_BASE+1)
OR   A
SBC  HL,DE
RET  C
ADD  HL,BC
RET  C
LD   E,(IX+NN_USED)
LD   D,(IX+NN_USED+1)
EX   DE,HL
OR   A
SBC  HL,DE
RET

; Validate entry and data-load rules that depend on this bank's used length.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_BANKSPECIAL:
LD   A,(IX+NN_BANKINDEX)
CP   (IX+NM_ENTRYBANK)
JR   NZ,NN_BSLOAD
LD   L,(IX+NM_ENTRY)
LD   H,(IX+NM_ENTRY+1)
LD   E,(IX+NB_BASE)
LD   D,(IX+NB_BASE+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
LD   E,(IX+NN_USED)
LD   D,(IX+NN_USED+1)
OR   A
SBC  HL,DE
JP   NC,NN_BAD
NN_BSLOAD:
BIT  0,(IX+NM_FLAGS)
JR   Z,NN_BSLOADED
LD   A,(IX+NN_BANKINDEX)
CP   (IX+NM_LOADBANK)
JR   NZ,NN_BSOK
LD   L,(IX+NM_LOAD)
LD   H,(IX+NM_LOAD+1)
LD   E,(IX+NB_BASE)
LD   D,(IX+NB_BASE+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
LD   E,(IX+NM_LOADLEN)
LD   D,(IX+NM_LOADLEN+1)
ADD  HL,DE
JP   C,NN_BAD
LD   E,(IX+NN_USED)
LD   D,(IX+NN_USED+1)
EX   DE,HL
OR   A
SBC  HL,DE
RET
NN_BSLOADED:
LD   A,(IX+NN_BANKINDEX)
OR   A
JR   NZ,NN_BSOK
LD   L,(IX+NB_BASE)
LD   H,(IX+NB_BASE+1)
LD   E,(IX+NN_USED)
LD   D,(IX+NN_USED+1)
ADD  HL,DE
JP   C,NN_BAD
LD   E,(IX+NM_IEND)
LD   D,(IX+NM_IEND+1)
OR   A
SBC  HL,DE
JP   NZ,NN_BAD
LD   L,(IX+NM_ENTRY)
LD   H,(IX+NM_ENTRY+1)
LD   E,(IX+NM_WBASE)
LD   D,(IX+NM_WBASE+1)
OR   A
SBC  HL,DE
JP   NC,NN_BAD
NN_BSOK:
XOR  A
RET

; Prove all PATCH intervals pairwise disjoint within their bank.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_PATCHCHECK:
XOR  A
LD   (IX+NN_PATCHINDEX),A
LD   (IX+NN_PATCHINDEX+1),A
NN_PCNEXT:
LD   L,(IX+NN_PATCHINDEX)
LD   H,(IX+NN_PATCHINDEX+1)
LD   E,(IX+NN_PATCHES)
LD   D,(IX+NN_PATCHES+1)
OR   A
SBC  HL,DE
RET  Z
CALL NN_FINDPATCH
RET  C
CALL NN_SCANPATCH
RET  C
LD   L,(IX+NN_PATCHINDEX)
LD   H,(IX+NN_PATCHINDEX+1)
INC  HL
LD   (IX+NN_PATCHINDEX),L
LD   (IX+NN_PATCHINDEX+1),H
JR   NN_PCNEXT

; Locate one PATCH by global ordinal and retain its relative interval.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_FINDPATCH:
CALL ZN_REW
RET  C
XOR  A
LD   (IX+NN_ORDINAL),A
LD   (IX+NN_ORDINAL+1),A
NN_FPHEAD:
CALL NN_HEAD
RET  C
CP   ZN_PATCH
JR   Z,NN_FPPATCH
CP   ZN_MAP
JP   Z,NN_BAD
CALL ZN_SETREM
CALL ZN_SKIP
RET  C
JR   NN_FPHEAD
NN_FPPATCH:
CALL NN_RANGE
RET  C
LD   L,(IX+NN_ORDINAL)
LD   H,(IX+NN_ORDINAL+1)
LD   E,(IX+NN_PATCHINDEX)
LD   D,(IX+NN_PATCHINDEX+1)
OR   A
SBC  HL,DE
JR   Z,NN_FPFOUND
LD   L,(IX+NN_ORDINAL)
LD   H,(IX+NN_ORDINAL+1)
INC  HL
LD   (IX+NN_ORDINAL),L
LD   (IX+NN_ORDINAL+1),H
CALL ZN_SKIP
RET  C
JR   NN_FPHEAD
NN_FPFOUND:
LD   A,(IX+NN_TMPBANK)
LD   (IX+NN_PBANK),A
LD   L,(IX+NN_TMPST)
LD   H,(IX+NN_TMPST+1)
LD   (IX+NN_PSTART),L
LD   (IX+NN_PSTART+1),H
LD   L,(IX+NN_TMPEND)
LD   H,(IX+NN_TMPEND+1)
LD   (IX+NN_PEND),L
LD   (IX+NN_PEND+1),H
CALL ZN_SKIP
RET

; Compare the retained PATCH with each earlier PATCH.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_SCANPATCH:
CALL ZN_REW
RET  C
XOR  A
LD   (IX+NN_ORDINAL),A
LD   (IX+NN_ORDINAL+1),A
NN_SPHEAD:
CALL NN_HEAD
RET  C
CP   ZN_PATCH
JR   Z,NN_SPPATCH
CP   ZN_MAP
JP   Z,NN_BAD
CALL ZN_SETREM
CALL ZN_SKIP
RET  C
JR   NN_SPHEAD
NN_SPPATCH:
CALL NN_RANGE
RET  C
LD   L,(IX+NN_ORDINAL)
LD   H,(IX+NN_ORDINAL+1)
LD   E,(IX+NN_PATCHINDEX)
LD   D,(IX+NN_PATCHINDEX+1)
OR   A
SBC  HL,DE
JR   Z,NN_SPDONE
LD   A,(IX+NN_TMPBANK)
CP   (IX+NN_PBANK)
JR   NZ,NN_SPNEXT
LD   L,(IX+NN_PSTART)
LD   H,(IX+NN_PSTART+1)
LD   E,(IX+NN_TMPEND)
LD   D,(IX+NN_TMPEND+1)
OR   A
SBC  HL,DE
JR   NC,NN_SPNEXT
LD   L,(IX+NN_TMPST)
LD   H,(IX+NN_TMPST+1)
LD   E,(IX+NN_PEND)
LD   D,(IX+NN_PEND+1)
OR   A
SBC  HL,DE
JP   C,NN_BAD
NN_SPNEXT:
LD   L,(IX+NN_ORDINAL)
LD   H,(IX+NN_ORDINAL+1)
INC  HL
LD   (IX+NN_ORDINAL),L
LD   (IX+NN_ORDINAL+1),H
CALL ZN_SKIP
RET  C
JR   NN_SPHEAD
NN_SPDONE:
CALL ZN_SKIP
RET

; Read and retain one record header.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_HEAD:
CALL ZN_READ
RET  C
LD   (IX+ZN_KIND),A
CALL ZN_READ
RET  C
LD   (IX+ZN_LENLO),A
CALL ZN_READ
RET  C
LD   (IX+ZN_LENHI),A
LD   A,(IX+ZN_KIND)
OR   A
RET

; Read an IMAGE/PATCH prefix and calculate its relative half-open interval.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_RANGE:
LD   L,(IX+ZN_LENLO)
LD   H,(IX+ZN_LENHI)
LD   DE,3
OR   A
SBC  HL,DE
RET  C
LD   A,H
OR   L
SCF
RET  Z
LD   (IX+ZN_REMLO),L
LD   (IX+ZN_REMHI),H
CALL ZN_READ
RET  C
CP   (IX+NB_BANKS)
RET  NC
LD   (IX+NN_TMPBANK),A
CALL NN_WORD
RET  C
LD   C,(IX+ZN_REMLO)
LD   B,(IX+ZN_REMHI)
LD   E,(IX+NB_BASE)
LD   D,(IX+NB_BASE+1)
OR   A
SBC  HL,DE
RET  C
LD   (IX+NN_TMPST),L
LD   (IX+NN_TMPST+1),H
ADD  HL,BC
RET  C
LD   (IX+NN_TMPEND),L
LD   (IX+NN_TMPEND+1),H
LD   E,(IX+NB_CAP)
LD   D,(IX+NB_CAP+1)
EX   DE,HL
OR   A
SBC  HL,DE
RET

; Read one little-endian word.
;@ROUTINE IN IX OUT A,HL,CARRY CLOBBERS BC,DE,ZERO,SIGN,PARITY,HALFCARRY
NN_WORD:
CALL ZN_READ
RET  C
LD   (IX+NN_WORDLO),A
CALL ZN_READ
RET  C
LD   H,A
LD   L,(IX+NN_WORDLO)
OR   A
RET

; Skip exactly HL bytes.
;@ROUTINE IN IX,HL OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
NN_SKIPN:
LD   (IX+ZN_REMLO),L
LD   (IX+ZN_REMHI),H
JP   ZN_SKIP

;@ROUTINE IN IX OUT CARRY CLOBBERS ZERO,SIGN,PARITY,HALFCARRY
@NN_FAIL:
SCF
RET

; Initialize every validated bank used extent before applying IMAGE/PATCH.
;@ROUTINE IN IX OUT A,CARRY CLOBBERS BC,DE,HL,ZERO,SIGN,PARITY,HALFCARRY
ZN_INIT:
XOR  A
LD   (IX+NN_BANKINDEX),A
NN_INITBANK:
CALL NN_BANKENTRY
RET  C
LD   L,(IX+NN_USED)
LD   H,(IX+NN_USED+1)
LD   (IX+ZN_REMLO),L
LD   (IX+ZN_REMHI),H
LD   L,(IX+NB_BASE)
LD   H,(IX+NB_BASE+1)
LD   (IX+ZN_ADDRLO),L
LD   (IX+ZN_ADDRHI),H
NN_INITBYTE:
LD   L,(IX+ZN_REMLO)
LD   H,(IX+ZN_REMHI)
LD   A,H
OR   L
JR   Z,NN_INITNEXT
DEC  HL
LD   (IX+ZN_REMLO),L
LD   (IX+ZN_REMHI),H
LD   A,(IX+NB_FILL)
LD   B,(IX+NN_BANKINDEX)
LD   E,(IX+ZN_ADDRLO)
LD   D,(IX+ZN_ADDRHI)
CALL ZN_STORE
RET  C
LD   L,(IX+ZN_ADDRLO)
LD   H,(IX+ZN_ADDRHI)
INC  HL
LD   (IX+ZN_ADDRLO),L
LD   (IX+ZN_ADDRHI),H
JR   NN_INITBYTE
NN_INITNEXT:
INC  (IX+NN_BANKINDEX)
LD   A,(IX+NN_BANKINDEX)
CP   (IX+NB_BANKS)
JR   C,NN_INITBANK
XOR  A
RET

NN_END:
